/* BD2 - 2o Bim -Atividade de SQL - Exercícios de DDL - Tabelas do Projeto Pedido - Parte 1
Queries implementadas na linguagem SQL aplicadas no SGBDR Oracle, apoiadas no
SqlDeveloper. Utilizar o MER Físico e BD Pedido disponibilizado para treinamento da disciplina
de Banco de Dados.
1) Implementar o script DDL para criar as tabelas do BD de pedidos: CLIENTE, PF, PJ,
PRODUTO, VENDEDOR, FONE_CLIENTE, FONE_VENDEDOR e PRATELEIRA.
Colocar as regras de integridade básica no script de criação. Substituir todos os tipos de
dados INTEGER que estão no modelo por NUMBER.
*/

DROP TABLE FONE_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE FONE_VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE PF CASCADE CONSTRAINTS;
DROP TABLE PJ CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE PRODUTO CASCADE CONSTRAINTS;
DROP TABLE PRATELEIRA CASCADE CONSTRAINTS;

CREATE TABLE CLIENTE (
    CODIGO NUMBER NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    RUA VARCHAR2(80) NOT NULL,
    NR NUMBER(4) NOT NULL,
    BAIRRO VARCHAR2(50) NOT NULL,
    COMPLEMENTO VARCHAR2(100),
    CIDADE VARCHAR2(50) NOT NULL,
    UF VARCHAR2(2) NOT NULL,
    CEP VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO)
);

CREATE TABLE VENDEDOR (
    MATRICULA NUMBER NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    CNPF VARCHAR2(14) NOT NULL,
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (MATRICULA)
);

CREATE TABLE PRODUTO (
    CODIGO NUMBER NOT NULL,
    DESCRICAO VARCHAR2(80) NOT NULL,
    UNID_MEDIDA VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO)
);

CREATE TABLE PRATELEIRA (
    CODIGO NUMBER(3) NOT NULL,
    DESCRICAO VARCHAR2(50) NOT NULL,
    NUMERO_SECOES NUMBER(2) NOT NULL,
    CONSTRAINT PK_PRATELEIRA PRIMARY KEY (CODIGO)
);

CREATE TABLE PF (
    CODIGO_CLI NUMBER NOT NULL,
    CNPF VARCHAR2(14) NOT NULL,
    RG VARCHAR2(10) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CONSTRAINT PK_CLIENTE_PF PRIMARY KEY (CODIGO_CLI),
    CONSTRAINT FK_PF_CLIENTE
        FOREIGN KEY (CODIGO_CLI)
        REFERENCES CLIENTE (CODIGO)
);

CREATE TABLE PJ (
    CODIGO_CLI NUMBER NOT NULL,
    CNPJ VARCHAR2(19) NOT NULL,
    IE VARCHAR2(10) NOT NULL,
    NOME_FANTASIA VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_CLIENTE_PJ PRIMARY KEY (CODIGO_CLI),
    CONSTRAINT FK_PJ_CLIENTE
        FOREIGN KEY (CODIGO_CLI)
        REFERENCES CLIENTE (CODIGO)
);

CREATE TABLE FONE_CLIENTE (
    NUMERO VARCHAR2(14) NOT NULL,
    CODIGO_CLI NUMBER NOT NULL,
    CONSTRAINT PK_FONE_CLIENTE PRIMARY KEY (NUMERO, CODIGO_CLI),
    CONSTRAINT FK_FONE_CLIENTE
        FOREIGN KEY (CODIGO_CLI)
        REFERENCES CLIENTE (CODIGO)
);

CREATE TABLE FONE_VENDEDOR (
    NUMERO VARCHAR2(14) NOT NULL,
    MATRICULA_VEN NUMBER NOT NULL,
    CONSTRAINT PK_FONE_VENDEDOR PRIMARY KEY (NUMERO, MATRICULA_VEN),
    CONSTRAINT FK_FONE_VENDEDOR
        FOREIGN KEY (MATRICULA_VEN)
        REFERENCES VENDEDOR (MATRICULA)
);