/*
BD2 - 2o Bim - Atividade de SQL - Exercícios de DDL - Comentários em tabelas - Parte 5
Queries implementadas na linguagem SQL aplicadas no SGBDR Oracle, apoiadas no
SqlDeveloper. Utilizar o MER Físico e BD Pedido disponibilizado para treinamento da disciplina
de Banco de Dados.
1) Criar comentários para a tabela ITEM_PRODUTO e suas respectivas colunas.
*/



-- CRIANDO TABELAS DEPENDENCIA

CREATE TABLE VENDEDOR (
    MATRICULA NUMBER NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    CNPF VARCHAR2(14) NOT NULL,
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (MATRICULA)
);

CREATE TABLE PRODUTO (
    CODIGO NUMBER NOT NULL,
    DESCRICAO VARCHAR2(80) NOT NULL,
    UNID_MEDIDA VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO)
);

-- TABELA ITEM_PRODUTO
CREATE TABLE ITEM_PRODUTO (
    CODIGO_PRO NUMBER NOT NULL,
    NUMERO_PED NUMBER(6) NOT NULL,
    QUANTIDADE NUMBER(5) NOT NULL,
    PRECO_UNITARIO NUMBER(5,2) NOT NULL,
    VALOR_ITEM NUMBER(7,2),

    CONSTRAINT PK_ITEM_PRODUTO
        PRIMARY KEY (CODIGO_PRO, NUMERO_PED),

    CONSTRAINT FK_ITEM_PEDIDO
        FOREIGN KEY (NUMERO_PED)
        REFERENCES PEDIDO (NUMERO),

    CONSTRAINT FK_ITEM_PRODUTO
        FOREIGN KEY (CODIGO_PRO)
        REFERENCES PRODUTO (CODIGO)
);

-- COMENTÁRIOS

COMMENT ON TABLE ITEM_PRODUTO IS
'Itens dos pedidos realizados';

COMMENT ON COLUMN ITEM_PRODUTO.CODIGO_PRO IS
'Código do produto';

COMMENT ON COLUMN ITEM_PRODUTO.NUMERO_PED IS
'Número do pedido';

COMMENT ON COLUMN ITEM_PRODUTO.QUANTIDADE IS
'Quantidade do produto no pedido';

COMMENT ON COLUMN ITEM_PRODUTO.PRECO_UNITARIO IS
'Preço unitário do produto';

COMMENT ON COLUMN ITEM_PRODUTO.VALOR_ITEM IS
'Valor total do item';










--Comment to add new commit message