/* BD2 - 2o Bim -Atividade de SQL - Exercícios de DML - Insert - Incluindo dados no Projeto
Pedido - Parte 1
Queries implementadas na linguagem SQL aplicadas no SGBDR Oracle, apoiadas no
SqlDeveloper. Utilizar o MER Físico e BD Pedido disponibilizado para treinamento da disciplina
de Banco de Dados.
1) Copiar os dados do projeto pedido cujo o owner seja o DEMO. Todas as tabelas do
usuário DEMO estão compartilhadas para leitura, exceto ITEM_PRODUTO.
*/

INSERT INTO CLIENTE SELECT * FROM DEMO.CLIENTE;
INSERT INTO VENDEDOR SELECT * FROM DEMO.VENDEDOR;
INSERT INTO PRODUTO SELECT * FROM DEMO.PRODUTO;
INSERT INTO PRATELEIRA SELECT * FROM DEMO.PRATELEIRA;

INSERT INTO PF SELECT * FROM DEMO.PF;
INSERT INTO PJ SELECT * FROM DEMO.PJ;
INSERT INTO FONE_CLIENTE SELECT * FROM DEMO.FONE_CLIENTE;
INSERT INTO FONE_VENDEDOR SELECT * FROM DEMO.FONE_VENDEDOR;

INSERT INTO PEDIDO SELECT * FROM DEMO.PEDIDO;
INSERT INTO ESTOQUE SELECT * FROM DEMO.ESTOQUE;
INSERT INTO CAPACIDADE_ESTOQUE SELECT * FROM DEMO.CAPACIDADE_ESTOQUE;

COMMIT;

-- Visualizando mudanças

/*
SELECT * FROM CLIENTE;
SELECT * FROM VENDEDOR;
SELECT * FROM PRODUTO;
SELECT * FROM  PRATELEIRA;

SELECT * FROM PF;
SELECT * FROM PJ;
SELECT * FROM FONE_CLIENTE;
SELECT * FROM FONE_VENDEDOR;

SELECT * FROM PEDIDO;
SELECT * FROM ESTOQUE;
SELECT * FROM CAPACIDADE_ESTOQUE;
*/
