/* BD2 - 2o Bim -Atividade de SQL - Exerc�cios de DDL - Tabelas do Projeto Pedido - Parte 1
Queries implementadas na linguagem SQL aplicadas no SGBDR Oracle, apoiadas no
SqlDeveloper. Utilizar o MER F�sico e BD Pedido disponibilizado para treinamento da disciplina
de Banco de Dados.
1) Implementar o script DDL para criar as tabelas do BD de pedidos: CLIENTE, PF, PJ,
PRODUTO, VENDEDOR, FONE_CLIENTE, FONE_VENDEDOR e PRATELEIRA.
Colocar as regras de integridade b�sica no script de cria��o. Substituir todos os tipos de
dados INTEGER que est�o no modelo por NUMBER.
*/


DROP TABLE FONE_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE FONE_VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE PF CASCADE CONSTRAINTS;
DROP TABLE PJ CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE PRODUTO CASCADE CONSTRAINTS;
DROP TABLE PRATELEIRA CASCADE CONSTRAINTS;

CREATE TABLE CLIENTE (
    CODIGO NUMBER NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    RUA VARCHAR2(80) NOT NULL,
    NR NUMBER(4) NOT NULL,
    BAIRRO VARCHAR2(50) NOT NULL,
    COMPLEMENTO VARCHAR2(100),
    CIDADE VARCHAR2(50) NOT NULL,
    UF VARCHAR2(2) NOT NULL,
    CEP VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO)
);

CREATE TABLE VENDEDOR (
    MATRICULA NUMBER NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    CNPF VARCHAR2(14) NOT NULL,
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (MATRICULA)
);

CREATE TABLE PRODUTO (
    CODIGO NUMBER NOT NULL,
    DESCRICAO VARCHAR2(80) NOT NULL,
    UNID_MEDIDA VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO)
);

CREATE TABLE PRATELEIRA (
    CODIGO NUMBER(3) NOT NULL,
    DESCRICAO VARCHAR2(50) NOT NULL,
    NUMERO_SECOES NUMBER(2) NOT NULL,
    CONSTRAINT PK_PRATELEIRA PRIMARY KEY (CODIGO)
);

CREATE TABLE PF (
    CODIGO_CLI NUMBER NOT NULL,
    CNPF VARCHAR2(14) NOT NULL,
    RG VARCHAR2(10) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CONSTRAINT PK_CLIENTE_PF PRIMARY KEY (CODIGO_CLI),
    CONSTRAINT FK_PF_CLIENTE
        FOREIGN KEY (CODIGO_CLI)
        REFERENCES CLIENTE (CODIGO)
);

CREATE TABLE PJ (
    CODIGO_CLI NUMBER NOT NULL,
    CNPJ VARCHAR2(19) NOT NULL,
    IE VARCHAR2(10) NOT NULL,
    NOME_FANTASIA VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_CLIENTE_PJ PRIMARY KEY (CODIGO_CLI),
    CONSTRAINT FK_PJ_CLIENTE
        FOREIGN KEY (CODIGO_CLI)
        REFERENCES CLIENTE (CODIGO)
);

CREATE TABLE FONE_CLIENTE (
    NUMERO VARCHAR2(14) NOT NULL,
    CODIGO_CLI NUMBER NOT NULL,
    CONSTRAINT PK_FONE_CLIENTE PRIMARY KEY (NUMERO, CODIGO_CLI),
    CONSTRAINT FK_FONE_CLIENTE
        FOREIGN KEY (CODIGO_CLI)
        REFERENCES CLIENTE (CODIGO)
);

CREATE TABLE FONE_VENDEDOR (
    NUMERO VARCHAR2(14) NOT NULL,
    MATRICULA_VEN NUMBER NOT NULL,
    CONSTRAINT PK_FONE_VENDEDOR PRIMARY KEY (NUMERO, MATRICULA_VEN),
    CONSTRAINT FK_FONE_VENDEDOR
        FOREIGN KEY (MATRICULA_VEN)
        REFERENCES VENDEDOR (MATRICULA)
); 



/*
SELECT * FROM CLIENTE;
SELECT * FROM VENDEDOR;
SELECT * FROM PRODUTO;
SELECT * FROM PRATELEIRA;
SELECT * FROM PF;
SELECT * FROM PJ;
SELECT * FROM FONE_CLIENTE;
SELECT * FROM FONE_VENDEDOR;
*/

/* BD2 - 2o Bim -Atividade de SQL - Exerc�cios de DDL - Tabelas do Projeto Pedido - Parte 2
Queries implementadas na linguagem SQL aplicadas no SGBDR Oracle, apoiadas no
SqlDeveloper. Utilizar o MER F�sico e BD Pedido disponibilizado para treinamento da disciplina
de Banco de Dados.
1) Criar as tabelas associativas: PEDIDO, ESTOQUE, CAPACIDADE_ESTOQUE e
ITEM_PRODUTO. N�o incluir na cria��o destas tabelas as chaves prim�ria (PK) e
chaves estrangeiras (FK). Substituir todos os tipos de dados INTEGER do modelo por
NUMBER.
2) Criar as constraints de chave prim�ria (primary key) para as tabelas associativas.
3) Criar as constraints das chaves estrangeiras (foreing key) para as tabelas associativas. */



DROP TABLE ITEM_PRODUTO CASCADE CONSTRAINTS;
DROP TABLE CAPACIDADE_ESTOQUE CASCADE CONSTRAINTS;
DROP TABLE ESTOQUE CASCADE CONSTRAINTS;
DROP TABLE PEDIDO CASCADE CONSTRAINTS;

----------------------------------------------------------------------------------

CREATE TABLE PEDIDO (
    NUMERO NUMBER(6) NOT NULL,
    DATA DATE NOT NULL,
    PRAZO_ENTREGA DATE,
    RUA VARCHAR2(80),
    NR NUMBER(4),
    BAIRRO VARCHAR2(50),
    COMPLEMENTO VARCHAR2(100),
    CIDADE VARCHAR2(50),
    UF VARCHAR2(2),
    CEP VARCHAR2(10),
    TOTAL_FATURA NUMBER(8,2),
    CODIGO_CLI NUMBER NOT NULL,
    MATRICULA_VEN NUMBER NOT NULL
);

CREATE TABLE ESTOQUE (
    DATA_ENTRADA DATE NOT NULL,
    CODIGO_PRO NUMBER NOT NULL,
    CODIGO_PRA NUMBER(3) NOT NULL,
    QUANTIDADE NUMBER(5) NOT NULL,
    DATA_VALIDADE DATE
);

CREATE TABLE CAPACIDADE_ESTOQUE (
    CODIGO_PRO NUMBER NOT NULL,
    CODIGO_PRA NUMBER(3) NOT NULL,
    QUANTIDADE NUMBER(5) NOT NULL
);

CREATE TABLE ITEM_PRODUTO (
    CODIGO_PRO NUMBER NOT NULL,
    NUMERO_PED NUMBER(6) NOT NULL,
    QUANTIDADE NUMBER(5) NOT NULL,
    PRECO_UNITARIO NUMBER(5,2) NOT NULL,
    VALOR_ITEM NUMBER(7,2)
);



-- Chaves pim�rias 



ALTER TABLE PEDIDO
ADD CONSTRAINT PK_PEDIDO
PRIMARY KEY (NUMERO);

ALTER TABLE ESTOQUE
ADD CONSTRAINT PK_ESTOQUE
PRIMARY KEY (CODIGO_PRO, CODIGO_PRA, DATA_ENTRADA);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT PK_CAPACIDADE_ESTOQUE
PRIMARY KEY (CODIGO_PRO, CODIGO_PRA);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT PK_ITEM_PRODUTO
PRIMARY KEY (CODIGO_PRO, NUMERO_PED);



-- CHAVES ESTRANGEIRAS 



ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_CLIENTE
FOREIGN KEY (CODIGO_CLI)
REFERENCES CLIENTE (CODIGO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_VENDEDOR
FOREIGN KEY (MATRICULA_VEN)
REFERENCES VENDEDOR (MATRICULA);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_EST_PRODUTO
FOREIGN KEY (CODIGO_PRO)
REFERENCES PRODUTO (CODIGO);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_EST_PRATELEIRA
FOREIGN KEY (CODIGO_PRA)
REFERENCES PRATELEIRA (CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAP_EST_PRODUTO
FOREIGN KEY (CODIGO_PRO)
REFERENCES PRODUTO (CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAP_EST_PRATELEIRA
FOREIGN KEY (CODIGO_PRA)
REFERENCES PRATELEIRA (CODIGO);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PEDIDO
FOREIGN KEY (NUMERO_PED)
REFERENCES PEDIDO (NUMERO);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PRODUTO
FOREIGN KEY (CODIGO_PRO)
REFERENCES PRODUTO (CODIGO);




/* TESTANDO CONSTRAISTS 

SELECT * FROM PEDIDO;
DESC PEDIDO;

DESC VENDEDOR;

INSERT INTO VENDEDOR (
    MATRICULA,
    NOME,
    CNPF
) VALUES (
    67,
    'PEDRO',
    '123.456.789'
)

SELECT * FROM VENDEDOR;

DESC CLIENTE;

INSERT INTO CLIENTE (
    CODIGO,
    NOME,
    RUA,
    NR,
    BAIRRO,
    CIDADE,
    UF,
    CEP
) VALUES (
    69,
    'VANDERSSON',
    'RUA DE LA',
    7,
    'BAIRRO DE CA',
    'GOIANIA',
    'GO',
    '80033020'
);

SELECT * FROM CLIENTE;

INSERT INTO PEDIDO (
    NUMERO,
    DATA,
    CODIGO_CLI,
    MATRICULA_VEN
) VALUES (
    1,
    TO_DATE('29/09/2026', 'DD/MM/YYYY'),
    69,
    67
);

*/


/* BD2 - 2o Bim -Atividade de SQL - Exercícios de DML - Insert - Incluindo dados no Projeto
Pedido - Parte 1
Queries implementadas na linguagem SQL aplicadas no SGBDR Oracle, apoiadas no
SqlDeveloper. Utilizar o MER Físico e BD Pedido disponibilizado para treinamento da disciplina
de Banco de Dados.
1) Copiar os dados do projeto pedido cujo o owner seja o DEMO. Todas as tabelas do
usuário DEMO estão compartilhadas para leitura, exceto ITEM_PRODUTO.
*/


/* Vizualizando TABLES DEMO 
SELECT TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'DEMO'
ORDER BY TABLE_NAME;

SELECT TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'BD22309389'
ORDER BY TABLE_NAME

SELECT * FROM DEMO.CLIENTE;

SELECT * FROM BD22309389.CLIENTE
*/

-- APAGANDO RESGISTROS

/*
DELETE FROM PEDIDO;
DELETE FROM CLIENTE;
DELETE FROM VENDEDOR;

COMMIT;
*/

INSERT INTO CLIENTE SELECT * FROM DEMO.CLIENTE;
INSERT INTO VENDEDOR SELECT * FROM DEMO.VENDEDOR;
INSERT INTO PRODUTO SELECT * FROM DEMO.PRODUTO;
INSERT INTO PRATELEIRA SELECT * FROM DEMO.PRATELEIRA;

INSERT INTO PF SELECT * FROM DEMO.PF;
INSERT INTO PJ SELECT * FROM DEMO.PJ;
INSERT INTO FONE_CLIENTE SELECT * FROM DEMO.FONE_CLIENTE;
INSERT INTO FONE_VENDEDOR SELECT * FROM DEMO.FONE_VENDEDOR;

INSERT INTO PEDIDO SELECT * FROM DEMO.PEDIDO;
INSERT INTO ESTOQUE SELECT * FROM DEMO.ESTOQUE;
INSERT INTO CAPACIDADE_ESTOQUE SELECT * FROM DEMO.CAPACIDADE_ESTOQUE;

COMMIT;

-- Visualizando mudanças

/*
SELECT * FROM CLIENTE;
SELECT * FROM VENDEDOR;
SELECT * FROM PRODUTO;
SELECT * FROM  PRATELEIRA;

SELECT * FROM PF;
SELECT * FROM PJ;
SELECT * FROM FONE_CLIENTE;
SELECT * FROM FONE_VENDEDOR;

SELECT * FROM PEDIDO;
SELECT * FROM ESTOQUE;
SELECT * FROM CAPACIDADE_ESTOQUE;
*/

